title: Site Title
name: Site Title
locale: en_us
description: >- 
  This is the site description
url: "www.example.com"
graph: "path/to/the/social/media/share/image"

sass:
  style: compressed
  sass_dir: _sass

author:
  twitter: TwitterUsername
